// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuNA9CB5g0sbquZehyDt2rInLqUMoCl-E',
    appId: '1:544117708493:web:cecec6316d420fbee33b84',
    messagingSenderId: '544117708493',
    projectId: 'drip-alart',
    authDomain: 'drip-alart.firebaseapp.com',
    storageBucket: 'drip-alart.appspot.com',
    measurementId: 'G-K0KTPQPY8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN8WuFfyMfqMvm2wa515pCYOUX53Kqlzk',
    appId: '1:544117708493:android:35a82f7b24036733e33b84',
    messagingSenderId: '544117708493',
    projectId: 'drip-alart',
    storageBucket: 'drip-alart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwLC16xfh_tmrfHR3P-CVSEcT_8RDPvQA',
    appId: '1:544117708493:ios:388fa661e54f60aee33b84',
    messagingSenderId: '544117708493',
    projectId: 'drip-alart',
    storageBucket: 'drip-alart.appspot.com',
    iosClientId: '544117708493-lnt7dihg1b9ifud9kgokojhlop8effhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwLC16xfh_tmrfHR3P-CVSEcT_8RDPvQA',
    appId: '1:544117708493:ios:5f207bd2920f949ae33b84',
    messagingSenderId: '544117708493',
    projectId: 'drip-alart',
    storageBucket: 'drip-alart.appspot.com',
    iosClientId: '544117708493-4pu6sc4hsb3jh7b2qlpj7beh0c07ru82.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainBox.RunnerTests',
  );
}
